metadata:
  namespace: cms
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/clcl0n/cms-image-service:latest

configuration:
  connectionStrings:
    mongoDb: mongodb://server:27017/cms-image-service?directConnection=true&tls=false&authSource=admin
  messagingBroker:
    rabbitMq:
      hostName: server
      port: 5672
      userName: rabbitmq
      password: rabbitmq
      virtualHost: /
      ssl:
        enabled: false
  externalStorage:
    s3ObjectStorage:
      accessKey: 5swEPvLY7pu8r7Aj8CbS
      secretKey: W4YAa2cwTsc15a9b3xvwt9RfcI0dpeZi8q1zGyxR
      serviceUrl: http://server:9000
      imageBucketName: images
      forcePathStyle: true