metadata:
  namespace: cms
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/clcl0n/cms-sitemap-service:latest

configuration:
  connectionStrings:
    mongoDb: mongodb://server:27017/cms-sitemap-service?directConnection=true&tls=false&authSource=admin
  messagingBroker:
    rabbitMq:
      hostName: server
      port: 5672
      userName: rabbitmq
      password: rabbitmq
      virtualHost: /
      ssl:
        enabled: false