metadata:
  namespace: cms
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/clcl0n/cms-site-service:latest

configuration:
  connectionStrings:
    mongoDb: mongodb://172.27.144.40:27017/cms-site-service?directConnection=true&tls=false&authSource=admin
  messagingBroker:
    rabbitMq:
      hostName: 172.27.144.40
      port: 5672
      userName: rabbitmq
      password: rabbitmq
      virtualHost: /
      ssl:
        enabled: false